@echo off
echo Cleaning dist folder...
if exist dist rmdir /s /q dist
echo Creating new dist folder...
mkdir dist
echo Skipping linting for now...
rem npx eslint --config .eslintrc.cjs components
echo Running build...
npx rollup --bundleConfigAsCjs --c build/rollup.config.js && npx bundlesize
echo Build complete! 